### ISSUE TITLE
[IMPORTANT] [1.18.2] Crash when Signal is over 15 

### ISSUE THREAD

**Issue by Camawama** [LIMachi/arss#2]
The entire server shuts down if someone gives a signal greater than 15 to a SIGNAL GENERATOR. There should be a failsafe to prevent this from happening (maybe the redstone signal becomes overloaded and shuts off or something). Someone could use this to intentionally crash the server.

This was tested while using the **ANALOGE LEVER** from **CREATE**.

I am playing on my own modpack CamaCraft on the public Magma server.
Modpack: https://www.curseforge.com/minecraft/modpacks/vanilla-plus-by-cama

[crash-2023-03-01_20.36.14-server.txt](https://github.com/LIMachi/arss/files/10865123/crash-2023-03-01_20.36.14-server.txt)

**Comment by Camawama** [comment]
I TESTED THIS AND CAN CONFIRM IT HAPPENS IN SINGLEPLAYER ON MY MODPACK AS WELL.

**Comment by LIMachi** [comment]
I will try to fix it (never expected the signal could go above the vanilla limit of 15, my bad i guess?)

**Comment by LIMachi** [comment]
Should be ok now, but since the 1.18.2 was behind the 1.19.2, I backported everything from 1.19.2 to 1.18.2 (this means that you will have to include my library in your modpack). How blocks works will be displayed by the info tab in JEI instead of on the tooltip, and additional info is accessible from The One Probe when looking at blocks.
I added some securities to make sure the generator (or any diode) will never try to generate a signal above 15.
I was unable to reproduce your crash since the analog levers from create can't generate a signal above 15 (without tinkering with the tile data), but it should work.

**Comment by LIMachi** [comment]
I realized I made a small, tiny, stupid mistake :P
When testing the new version against your modpack I found 2 new problems:
-Incompatible forge versions (I need to change the forge version, it shouldn't be too hard)
-Due to the way I implemented the compatibility with The One Probe, TOP is currently required for the mod and library to load, this on the other hand will take a little more time to fix (I'll try to do it later, it's 12:10 AM and I have work tomorrow/today).

**Comment by Camawama** [comment]
This is wonderful to wake up to! Thank you for your hard work and thank you for such a creative and amazing mod. I will do the testing tonight and verify all is working!!

**Comment by LIMachi** [comment]
I'm finishing some test, but if all is good, the new version compatible with the newer versions of forge and without crash if TOP is missing should be uploaded in 1-2 hours

**Comment by Camawama** [comment]
Happy to report that it's working perfectly! Thank you for this absolutely fantastic mod!
